version: 6

aliases:
  human: true
  snpeff: hg19
  ensembl: human

variation:
  dbsnp: ../variation/dbsnp_138.vcf.gz
  train_hapmap: ../variation/hapmap_3.3.vcf.gz
  train_1000g_omni: ../variation/1000G_omni2.5.vcf.gz
  train_indels: ../variation/Mills_and_1000G_gold_standard.indels.vcf.gz
  cosmic: ../variation/cosmic-v68-hg19.vcf.gz

rnaseq:
  transcripts: ../rnaseq/ref-transcripts.gtf
  transcripts_mask: ../rnaseq/ref-transcripts-mask.gtf
  transcriptome_index:
    tophat: ../rnaseq/tophat/hg19_transcriptome.ver
